### PR TITLE
Tb search all

### PR DESCRIPTION
**Pull request by ToniJBaker**
# Description

Describe your changes, and why you're making them. Is this linked to an open issue, a Trello card, or another pull request? Link it here.
Ticket #14 
SearchManager Line 102-122  Method SearchAll()
                          Line 40 call SearchAll()

# Testing Instructions
Should be able to use the search all feature and search for tag: nerdy
only a single author should appear.  Nothing for blogs or posts-Search Results should be blank.

Make your instructions ***explicit***.
State which branch, link any seed data, any data they need to enter to have the feature perform correctly, step by step of exactly what they should see

# Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings or errors
- [x ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by nthi — COMMENTED** [review]
Here's what I get with a Search All for "nerdy." Is this the format that successful searches will look like? It looks like for me no author? Yes a generic post object? and yes a specific blog?


Search Results 

Search Results
TabloidClI.Models.Post

Search Results
The Data Farm ....

**Comment by ToniJBaker** [comment]
Natalie, that sounds right based on the tags you have in your local database and what tags you have linked to each author, blog or post.
I the tag nerdy attached to the 3rd Author Felienne Hermans, so her name appears in the first Search Results location.

**Review by nthi — APPROVED** [review]
OKAY I'm silly. I tagged an author and tested that.

I get the author tagged
A generic TabloidCLI.Models.Post
The blog post

good to go I believe

**Review by bgizzle78 — APPROVED** [review]
Search all feature tested and confirmed working.

**Pull request merged**
